/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Provider type enum for JavaScript. */
export const enum ProviderType {
  OpenAI = 'OpenAI',
  Anthropic = 'Anthropic',
  Ollama = 'Ollama',
  Gemini = 'Gemini',
  Grok = 'Grok'
}
/** Configuration for AI providers. */
export interface ProviderConfig {
  provider: ProviderType
  model?: string
  apiKey?: string
  baseUrl?: string
  maxTokens?: number
  temperature?: number
}
/**
 * One-line code generation function.
 *
 * # Example
 * ```javascript
 * const code = await generate("Create a login form");
 * ```
 */
export declare function generate(prompt: string, provider?: string | undefined | null): Promise<string>
/** Quick template rendering. */
export declare function renderTemplate(content: string, slots: Record<string, string>): Promise<string>
/** JavaScript-accessible Template class. */
export declare class Template {
  /**
   * Create a new template from content string.
   *
   * Use `{{AI:slot_name}}` syntax to define injection points.
   */
  constructor(content: string)
  /** Set the template name. */
  setName(name: string): void
  /** Add a slot with a prompt. */
  setSlot(name: string, prompt: string): void
  /** Get all slot names in this template. */
  getSlotNames(): Array<string>
  /** Get the template content. */
  get content(): string
}
/** JavaScript-accessible Slot class. */
export declare class Slot {
  /** Create a new slot. */
  constructor(name: string, prompt: string)
  /** Set the slot kind. */
  setKind(kind: string): void
  /** Set maximum lines constraint. */
  setMaxLines(max: number): void
}
/** Main Aether engine for JavaScript. */
export declare class AetherEngine {
  /** Create a new engine with OpenAI provider. */
  static openai(model?: string | undefined | null): AetherEngine
  /** Create a new engine with Anthropic provider. */
  static anthropic(model?: string | undefined | null): AetherEngine
  /** Create a new engine with Gemini provider. */
  static gemini(model?: string | undefined | null): AetherEngine
  /** Create a new engine with Ollama provider. */
  static ollama(model?: string | undefined | null): AetherEngine
  /** Create a new engine with Grok provider. */
  static grok(model?: string | undefined | null): AetherEngine
  /** Set the API key. */
  setApiKey(key: string): void
  /** Set context for generation. */
  setContext(project?: string | undefined | null, language?: string | undefined | null, framework?: string | undefined | null): void
  /** Enable or disable parallel generation. */
  setParallel(enabled: boolean): void
  /** Set maximum retries. */
  setMaxRetries(retries: number): void
  /** Enable or disable self-healing. */
  setHeal(enabled: boolean): void
  /** Enable or disable semantic caching. */
  setCache(enabled: boolean): void
  /** Enable or disable TOON formatting. */
  setToon(enabled: boolean): void
  /** Generate code with a simple prompt (one-liner). */
  generate(prompt: string): Promise<string>
  /** Render a template with AI-generated code. */
  render(template: Template): Promise<string>
}
