name: 💡 Feature Request
description: Suggest an idea for this project
title: "[Feat]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving Aether!
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when I have to...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: It would be great if Aether could...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How critical is this feature for you?
      options:
        - Critical (Blocking my work)
        - High (Needed soon)
        - Medium (Nice to have)
        - Low (Maybe someday)
